# Generated by Django 4.2 on 2023-11-08 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_invoices_delete_invoices_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoices_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=None, max_digits=8, null=True)),
                ('invoice_item_description', models.CharField(max_length=255)),
                ('remark', models.CharField(max_length=255)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.invoices')),
            ],
        ),
    ]
