# Generated by Django 4.2 on 2023-12-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_invoices_receipt_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='targeted_group',
            field=models.CharField(choices=[('ALL', 'All Users'), ('ADMIN', 'Administrators'), ('STUDENT', 'Students')], default='ALL', max_length=20),
        ),
    ]
