# Generated by Django 4.2 on 2023-12-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_alter_announcement_announcement_posted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='receipt_pdf_sent',
            field=models.FileField(null=True, upload_to='receipt_pdf_sent/'),
        ),
    ]
