# Generated by Django 4.2 on 2023-12-10 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0054_invoices_receipt_pdf_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoices',
            name='receipt_pdf_sent',
        ),
        migrations.CreateModel(
            name='Receipts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_no', models.CharField(max_length=20)),
                ('receipt_pdf_sent', models.FileField(null=True, upload_to='receipt_pdf_sent/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.invoices')),
            ],
        ),
    ]
