# Generated by Django 4.2 on 2023-12-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0055_remove_invoices_receipt_pdf_sent_receipts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices_items',
            name='remark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
