# Generated by Django 4.2 on 2024-01-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0060_user_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuition_classes',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
